title: "Toward Useful Systems for Useful Agentic AI"
name: "Agentic AI Research Collaboration"
description: "A collaboration of over 20 researchers across UC Berkeley, Intesa Sanpaolo, IBM Research, UIUC, and Stanford working on industry-grade agentic AI systems."
url:
baseurl:
permalink: pretty
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: default
plugins:
  - jekyll-include-cache
