title: "Toward Useful Systems for Useful Agentic AI"
name: "Agentic AI Research Collaboration"
description: "A collaboration of over 20 researchers across UC Berkeley, Intesa Sanpaolo, IBM Research, UIUC, and Stanford working on industry-grade agentic AI systems."
url:
baseurl:
permalink: pretty
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: air
plugins:
  - jekyll-include-cache

# Berkeley theme customizations
author:
  name: "UC Berkeley Research Team"
  avatar: "https://brand.berkeley.edu/wp-content/uploads/2016/10/ucbseal_139_540.png"
  bio: "Agentic AI Research Collaboration"
  location: "Berkeley, CA"
  links:
    - label: "UC Berkeley"
      icon: "fas fa-university"
      url: "https://berkeley.edu"

# Site subtitle for header
site_subtitle: "UC Berkeley • Stanford • IBM Research • Intesa Sanpaolo • UIUC"
